# 基础键值对
name: "YinKang'an"
age: 18
score: 99
is_student: true
bilibili: https://b23.tv/zG8SQIQ
github: https://github.com/YingKang-an/CPlusPlus_study_notes.git

# 嵌套层级
address:
  province: "辽宁省"
  city: "大连市"
  detail: "甘井子区"

# 列表/数组
hobbies:
  - C
  - C++
  - OpenCV

# 复杂列表（每个元素是对象）
scores:
  - subject: "高等数学"
    score: 90
  - subject: "线性代数"
    score: 92