# 相机配置参数
camera:
  Model: "MER-139-210U3C"
  Exposure: 3934.0
  Gain: 8.514
  whiteBalance:
    Blue: 2.1175
    Green: 0.1850
    Red: 1.5135

# 标定参数
calibration:
  board_size: [9, 6]  # 棋盘格内角点数量
  square_size: 8.5    # 棋盘格方格大小(mm)
  min_images: 10      # 最小标定图像数量